In [169]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from scipy.stats import spearmanr

In [43]:
data_chicken = pd.read_csv('TranscriptomeData/Nomi_chickenDEGs.csv', header=0)
data_chicken = data_chicken.rename(columns={'Unnamed: 0': 'Name'});

In [44]:
data_mouse = pd.read_csv('TranscriptomeData/Nomi_mouseDEGs.csv', header=0)
data_mouse = data_mouse.rename(columns={'Unnamed: 0': 'Name'});

In [98]:
data_human = pd.read_csv('TranscriptomeData/Nomi_humanDEGs.csv', header=0)
data_human = data_human.rename(columns={'Unnamed: 0': 'Name'});

In [99]:
common_genes = np.intersect1d(np.intersect1d(data_chicken['gene'], data_mouse['gene']), data_human['gene'])

In [100]:
data_human = data_human.loc[data_human['gene'].isin(common_genes)]
data_chicken = data_chicken.loc[data_chicken['gene'].isin(common_genes)]
data_mouse = data_mouse.loc[data_mouse['gene'].isin(common_genes)]

In [102]:
data_human.loc[:, ('p_val_adj')] /= data_human.loc[:, ('p_val_adj')].mean()

In [103]:
data_human

,Name,p_val,avg_logFC,pct.1,pct.2,p_val_adj,cluster,gene
0,Kcnip4,1.839865e-76,0.757675,1.000,1.000,3.967211e-72,Lat.B1,Kcnip4
1,Pde10a,7.904878e-72,1.851922,0.991,0.868,1.704490e-67,Lat.B1,Pde10a
2,Sorcs1,8.414871e-65,1.122925,1.000,0.993,1.814458e-60,Lat.B1,Sorcs1
3,Cdh8,2.515441e-64,1.398988,0.993,0.812,5.423924e-60,Lat.B1,Cdh8
4,Ebf2,1.124721e-54,-2.832642,0.768,0.938,2.425181e-50,Lat.B1,Ebf2
...,...,...,...,...,...,...,...,...
9654,Tomm70a.1,9.624536e-03,0.535468,0.897,0.628,1.819775e+00,IntA.B2,Tomm70a
9655,Pcp4.3,9.650591e-03,-1.154234,0.828,0.854,1.819775e+00,IntA.B2,Pcp4
9658,Aars,9.720015e-03,0.286059,0.897,0.793,1.819775e+00,IntA.B2,Aars
9661,P2rx6.2,9.727655e-03,1.040700,0.621,0.467,1.819775e+00,IntA.B2,P2rx6
9663,Abat,9.742413e-03,0.307708,0.966,0.930,1.819775e+00,IntA.B2,Abat

In [118]:
average_chicken = pd.read_csv('TranscriptomeData/Nomi_chickenallaverage.csv', header=0, index_col=0)

,RNA.Med.A1,RNA.MedL.A1,RNA.IntP.A1,RNA.IntP.A2,RNA.IntX.A1,RNA.IntX.A2,RNA.IntX.A3,RNA.Med.B1,RNA.Med.B2,RNA.Med.B3,RNA.Med.B4,RNA.Med.B5,RNA.MedL.B1,RNA.IntP.B1,RNA.IntP.B2,RNA.IntX.B1,RNA.IntX.B2
Panx2,33.611120,107.376900,52.985213,52.000306,129.396251,66.716160,100.804938,46.060321,49.153706,78.465540,64.325776,79.960418,70.003389,46.501843,64.326021,109.668925,93.235176
2310057M21Rik,24.626831,14.702946,12.929836,15.088088,20.964924,9.673169,8.050549,72.438854,10.831207,14.404892,9.520570,5.450726,22.698655,30.522908,41.867589,10.366234,30.795654
Wfikkn1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Lamtor3,262.078246,58.638357,33.985174,71.594571,65.723832,57.625919,70.056136,190.878887,62.390666,50.406891,52.979441,44.854799,107.270317,95.142415,85.844595,66.215426,80.917735
Spr,132.259471,58.749017,40.510482,56.250411,54.449795,135.867789,106.153128,111.727223,100.715293,38.918520,73.575213,47.839570,47.904549,40.440680,40.656892,26.849460,93.240867
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ENSMUSG00000024786,0.959312,0.050350,0.900876,0.445543,1.401749,0.073883,0.194218,0.447407,0.744020,0.740168,0.111649,0.434275,0.373969,0.982619,4.832596,1.419168,2.714663
ENSMUSG00000032648,0.000000,0.261759,0.000000,0.203689,0.123361,0.000000,0.057203,0.000000,0.000000,0.079990,0.206152,0.050002,0.000000,0.000000,0.000000,0.112665,0.000000
ENSMUSG00000025758,0.100879,0.068535,0.129579,0.000000,0.275235,0.359552,0.000000,0.000000,0.095964,0.000000,0.000000,0.083839,0.084934,0.000000,0.159543,0.000000,0.121131
ENSMUSG00000053460,0.347329,0.000000,0.414164,0.146967,0.000000,0.000000,0.061170,0.209929,0.000000,0.000000,0.000000,0.035458,0.093992,0.000000,0.077042,0.000000,0.091325
ENSMUSG00000071652,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [142]:
average_chicken = average_chicken.loc[average_chicken.index.isin(common_genes)]
average_chicken

,RNA.Med.A1,RNA.MedL.A1,RNA.IntP.A1,RNA.IntP.A2,RNA.IntX.A1,RNA.IntX.A2,RNA.IntX.A3,RNA.Med.B1,RNA.Med.B2,RNA.Med.B3,RNA.Med.B4,RNA.Med.B5,RNA.MedL.B1,RNA.IntP.B1,RNA.IntP.B2,RNA.IntX.B1,RNA.IntX.B2
Lamtor3,262.078246,58.638357,33.985174,71.594571,65.723832,57.625919,70.056136,190.878887,62.390666,50.406891,52.979441,44.854799,107.270317,95.142415,85.844595,66.215426,80.917735
Cept1,139.223907,79.829335,30.632325,66.088992,62.240780,102.898896,55.979600,132.868598,148.912426,65.485639,89.537404,94.820912,65.088395,65.867054,39.605085,44.695640,66.963042
Supt6,64.637063,39.015955,101.004965,28.811363,36.535371,32.517381,55.729316,52.855550,106.634449,27.916304,50.472885,34.973377,45.216133,20.875005,40.054234,27.551728,65.872396
Ythdc2,12.751096,126.943922,81.879931,159.141391,171.960056,121.924703,205.548449,17.611724,281.863727,255.027264,318.319501,336.746521,219.387241,228.112080,148.781322,243.584675,263.701573
Mcc,55.212205,78.950094,125.552149,147.010286,64.093579,100.368164,94.768308,168.314006,70.553645,169.565493,161.407884,175.637325,105.483674,189.890264,99.824337,174.856493,132.059681
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ENSMUSG00000037119,1.086857,28.352973,2.751231,19.564593,28.291046,33.457654,17.150057,6.033648,30.930569,17.966928,32.170634,40.175140,25.690956,6.005851,53.837592,19.880002,38.120745
ENSMUSG00000025429,1.772107,0.000000,0.366141,0.000000,0.164339,0.195268,0.175376,4.349973,0.241957,1.041864,1.115881,0.765208,0.038870,0.291358,0.052961,1.147608,0.031128
ENSMUSG00000069806,1.462577,11.255827,0.000000,2.602078,4.256329,1.484756,1.593115,4.030313,4.698064,5.219289,2.067076,6.587081,4.969292,1.936536,1.700577,4.590207,1.548491
ENSMUSG00000021879,3.793964,87.644568,91.218366,60.221174,29.999992,45.962178,34.131791,7.692878,72.183636,57.477794,60.071223,83.114985,74.379399,19.478671,43.466970,46.504753,62.225650
ENSMUSG00000060798,1.157485,7.894132,13.778385,4.567657,26.338528,26.128653,18.282447,11.088134,5.438326,8.083201,13.840644,12.397635,11.985748,1.273175,12.861777,16.866783,4.811441

In [159]:
(average_chicken.div(average_chicken.mean(axis=1).values, axis=0) == np.inf).values.any()

False

In [189]:
average_chicken_T=average_chicken.add_prefix('C_').transpose().to_numpy()

In [191]:
average_chicken_T.shape

(17, 2359)

In [196]:
rho, pval = spearmanr(average_chicken_T, average_chicken_T)

In [197]:
rho

array([[ 1.        ,  0.09803922,  0.08578431, ..., -0.21078431,
        -0.59558824, -0.43382353],
       [ 0.09803922,  1.        ,  0.21078431, ...,  0.12009804,
        -0.09313725, -0.42401961],
       [ 0.08578431,  0.21078431,  1.        , ..., -0.36519608,
         0.18137255, -0.08088235],
       ...,
       [-0.21078431,  0.12009804, -0.36519608, ...,  1.        ,
         0.35294118, -0.04901961],
       [-0.59558824, -0.09313725,  0.18137255, ...,  0.35294118,
         1.        , -0.01470588],
       [-0.43382353, -0.42401961, -0.08088235, ..., -0.04901961,
        -0.01470588,  1.        ]])

In [200]:
rho, pval = spearmanr(average_chicken_T, axis=1)

In [202]:
rho.shape

(17, 17)

In [204]:
from scipy.special import comb

In [209]:
comb(17, list(range(1,18))).sum()

131071.0

In [210]:
average_chicken

,RNA.Med.A1,RNA.MedL.A1,RNA.IntP.A1,RNA.IntP.A2,RNA.IntX.A1,RNA.IntX.A2,RNA.IntX.A3,RNA.Med.B1,RNA.Med.B2,RNA.Med.B3,RNA.Med.B4,RNA.Med.B5,RNA.MedL.B1,RNA.IntP.B1,RNA.IntP.B2,RNA.IntX.B1,RNA.IntX.B2
Lamtor3,262.078246,58.638357,33.985174,71.594571,65.723832,57.625919,70.056136,190.878887,62.390666,50.406891,52.979441,44.854799,107.270317,95.142415,85.844595,66.215426,80.917735
Cept1,139.223907,79.829335,30.632325,66.088992,62.240780,102.898896,55.979600,132.868598,148.912426,65.485639,89.537404,94.820912,65.088395,65.867054,39.605085,44.695640,66.963042
Supt6,64.637063,39.015955,101.004965,28.811363,36.535371,32.517381,55.729316,52.855550,106.634449,27.916304,50.472885,34.973377,45.216133,20.875005,40.054234,27.551728,65.872396
Ythdc2,12.751096,126.943922,81.879931,159.141391,171.960056,121.924703,205.548449,17.611724,281.863727,255.027264,318.319501,336.746521,219.387241,228.112080,148.781322,243.584675,263.701573
Mcc,55.212205,78.950094,125.552149,147.010286,64.093579,100.368164,94.768308,168.314006,70.553645,169.565493,161.407884,175.637325,105.483674,189.890264,99.824337,174.856493,132.059681
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ENSMUSG00000037119,1.086857,28.352973,2.751231,19.564593,28.291046,33.457654,17.150057,6.033648,30.930569,17.966928,32.170634,40.175140,25.690956,6.005851,53.837592,19.880002,38.120745
ENSMUSG00000025429,1.772107,0.000000,0.366141,0.000000,0.164339,0.195268,0.175376,4.349973,0.241957,1.041864,1.115881,0.765208,0.038870,0.291358,0.052961,1.147608,0.031128
ENSMUSG00000069806,1.462577,11.255827,0.000000,2.602078,4.256329,1.484756,1.593115,4.030313,4.698064,5.219289,2.067076,6.587081,4.969292,1.936536,1.700577,4.590207,1.548491
ENSMUSG00000021879,3.793964,87.644568,91.218366,60.221174,29.999992,45.962178,34.131791,7.692878,72.183636,57.477794,60.071223,83.114985,74.379399,19.478671,43.466970,46.504753,62.225650
ENSMUSG00000060798,1.157485,7.894132,13.778385,4.567657,26.338528,26.128653,18.282447,11.088134,5.438326,8.083201,13.840644,12.397635,11.985748,1.273175,12.861777,16.866783,4.811441